/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { 
  Database, 
  Settings, 
  CheckCircle, 
  AlertCircle, 
  Cpu, 
  Server, 
  UserCheck, 
  ArrowLeft, 
  ArrowRight, 
  Code, 
  Lock, 
  FileCheck,
  RefreshCw,
  Terminal,
  Download
} from 'lucide-react';

interface PHPInstallerSimProps {
  onClose: () => void;
  triggerToast: (title: string, message: string, type: 'success' | 'error' | 'warning') => void;
}

export default function PHPInstallerSim({ onClose, triggerToast }: PHPInstallerSimProps) {
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  
  // DB Config State
  const [dbHost, setDbHost] = useState('127.0.0.1');
  const [dbPort, setDbPort] = useState('3306');
  const [dbName, setDbName] = useState('almakhzoun_pro_db');
  const [dbUser, setDbUser] = useState('root');
  const [dbPass, setDbPass] = useState('');

  // Admin Config State
  const [adminName, setAdminName] = useState('');
  const [adminUser, setAdminUser] = useState('');
  const [adminPass, setAdminPass] = useState('');
  const [adminEmail, setAdminEmail] = useState('');
  const [adminPhone, setAdminPhone] = useState('');

  // Simulation Logs state
  const [consoleLogs, setConsoleLogs] = useState<string[]>([]);

  // Step 1 check states
  const [checks, setChecks] = useState({
    phpVersion: '8.2.14',
    pdo: true,
    pdoMysql: true,
    gd: true,
    zip: true,
    configWritable: true,
    storageWritable: true
  });

  const runTestConnection = () => {
    setLoading(true);
    setErrorMsg('');
    setTimeout(() => {
      setLoading(false);
      if (dbName.trim() === '' || dbUser.trim() === '') {
        setErrorMsg('فشل الاتصال: اسم قاعدة البيانات واسم المستخدم حقول إجبارية في بيئة MySQL.');
      } else {
        triggerToast('نجاح الاتصال', 'تم الاتصال بقاعدة بيانات MySQL المحددة بنجاح وتأكيد وجود الصلاحيات!', 'success');
        setStep(3);
      }
    }, 1500);
  };

  const runInstallerAndCreateAdmin = () => {
    if (!adminName || !adminUser || !adminPass) {
      setErrorMsg('الرجاء تعبئة بيانات المدير الرئيسي الإجبارية (الاسم، اسم المستخدم، الرقم السري).');
      return;
    }

    setLoading(true);
    setErrorMsg('');
    setConsoleLogs([
      '⏱️ جاري بدء معالج التثبيت التلقائي...',
      `📡 جاري إنشاء قاعدة البيانات \`${dbName}\` إذا لم تكن موجودة...`,
      '✓ قاعدة البيانات جاهزة ومهيئة بصيغة الترميز الموحد utf8mb4_unicode_ci.',
      '📂 جاري قراءة ملف الاستيراد الرئيسي database/database.sql...',
      '✓ تم تحميل ملف SQL المصدري بنجاح (طول الملف: 5,420 بايت).',
      '⚡ جاري استيراد جدول الفروع والمواقع (branches)...',
      '⚡ جاري استيراد جدول المستخدمين وإعداد الهيكل العام (users)...',
      '⚡ جاري استيراد جدول السيارات والمخزون الممتد (cars)...',
      '⚡ جاري استيراد جدول الحجوزات وطلبات المعارض (reservations)...',
      '⚡ جاري استيراد جدول سجل العمليات والرقابة (system_logs)...',
      '⚡ جاري استيراد جدول إعدادات المؤسسة العامة (settings)...',
      '✓ تم استيراد الجداول الـ 6 الرئيسية وربط العلاقات والمفاتيح الخارجية بنجاح.',
      `👤 جاري تشفير كلمة المرور وتوليد حساب المدير الرئيسي: "${adminName}" (${adminUser})...`,
      '✓ تم إدراج حساب المدير وصلاحيات الإشراف والرقابة المطلقة بنجاح.',
      '⚙️ جاري توليد ملف الإعدادات المركزي config/config.php...',
      '🔒 جاري تأمين معالج التثبيت وإنشاء ملف القفل الحركي storage/install.lock...',
      '🎉 عملية التثبيت والتهيئة المتكاملة اكتملت بنجاح مطلق!'
    ]);

    let logIndex = 0;
    const interval = setInterval(() => {
      logIndex += 1;
      if (logIndex >= 17) {
        clearInterval(interval);
        setLoading(false);
        setStep(4);
        triggerToast('تثبيت ناجح', 'تهانينا! تم تثبيت نظام المخزون وإنشاء حساب المدير بنجاح تام.', 'success');
      }
    }, 200);
  };

  const downloadConfigPhp = () => {
    const fileContent = `<?php
/**
 * Generated by Almakhzoun Pro Installation Wizard
 * Date: ${new Date().toISOString()}
 */

return [
    'db' => [
        'host' => '${dbHost}',
        'port' => ${dbPort},
        'dbname' => '${dbName}',
        'username' => '${dbUser}',
        'password' => '${dbPass}',
        'charset' => 'utf8mb4',
    ],
    'app' => [
        'name' => 'Almakhzoun Pro ERP',
        'version' => '2.0.0',
        'installed_at' => '${new Date().toISOString()}',
    ]
];
`;
    const blob = new Blob([fileContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'config.php';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    triggerToast('تنزيل الملف', 'تم تنزيل ملف config.php المولد تلقائياً بنجاح!', 'success');
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex justify-center items-center p-4 overflow-y-auto text-right">
      <div className="w-full max-w-2xl bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden flex flex-col">
        
        {/* Progress bar */}
        <div className="h-1.5 w-full bg-slate-800 relative">
          <div 
            className="h-full bg-gradient-to-l from-indigo-500 to-indigo-600 transition-all duration-300" 
            style={{ width: `${step * 25}%` }}
          ></div>
        </div>

        {/* Header */}
        <div className="p-5 border-b border-slate-800 flex justify-between items-center bg-slate-950/40">
          <div>
            <span className="text-[10px] bg-indigo-500/10 text-indigo-400 font-bold px-2 py-0.5 rounded-full">
              الخطوة {step} من 4
            </span>
            <h3 className="font-extrabold text-sm text-white mt-1">
              {step === 1 && 'الخطوة 1: فحص بيئة السيرفر ومتطلبات التشغيل'}
              {step === 2 && 'الخطوة 2: تهيئة واختبار اتصال قاعدة البيانات'}
              {step === 3 && 'الخطوة 3: إعداد حساب مدير النظام الأول'}
              {step === 4 && 'تهانينا! اكتمل التثبيت والتهيئة بنجاح'}
            </h3>
          </div>
          <button 
            onClick={onClose}
            className="text-xs text-slate-500 hover:text-white transition-colors border border-slate-800 hover:border-slate-700 px-2.5 py-1 rounded bg-slate-900 cursor-pointer"
          >
            إغلاق المعالج
          </button>
        </div>

        {/* Error message */}
        {errorMsg && (
          <div className="mx-5 mt-4 p-3 bg-rose-500/10 border border-rose-500/20 text-rose-400 text-xs font-bold rounded-lg flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{errorMsg}</span>
          </div>
        )}

        {/* Content Body */}
        <div className="p-6 flex-1 overflow-y-auto max-h-[450px]">
          
          {/* STEP 1: SERVER REQUIREMENT CHECKS */}
          {step === 1 && (
            <div className="space-y-4">
              <p className="text-xs text-slate-400 leading-relaxed">
                يقوم معالج التثبيت أمنياً بفحص مميزات السيرفر وملحقات PHP المتاحة لضمان تشغيل لوحة التحكم وعمليات الرقابة وتشفير الجلسات بأمان كامل على خوادم الاستضافة المشتركة أو الخوادم الخاصة:
              </p>

              <div className="space-y-2.5">
                <div className="flex items-center justify-between p-3 bg-slate-950/50 border border-slate-800 rounded-lg">
                  <div className="flex items-center gap-2">
                    <Cpu className="w-4 h-4 text-indigo-400" />
                    <span className="text-xs text-slate-200">إصدار PHP (يشترط 8.2.0 أو أحدث)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] font-sans text-slate-500">(الإصدار الحالي: {checks.phpVersion})</span>
                    <span className="text-[10px] font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2 py-0.5 rounded">متوافق ✓</span>
                  </div>
                </div>

                <div className="flex items-center justify-between p-3 bg-slate-950/50 border border-slate-800 rounded-lg">
                  <div className="flex items-center gap-2">
                    <Server className="w-4 h-4 text-indigo-400" />
                    <span className="text-xs text-slate-200">امتداد قاعدة البيانات PDO Extension</span>
                  </div>
                  <span className="text-[10px] font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2 py-0.5 rounded">مفعل ونشط ✓</span>
                </div>

                <div className="flex items-center justify-between p-3 bg-slate-950/50 border border-slate-800 rounded-lg">
                  <div className="flex items-center gap-2">
                    <Database className="w-4 h-4 text-indigo-400" />
                    <span className="text-xs text-slate-200">مشغّل اتصال PDO MySQL Driver</span>
                  </div>
                  <span className="text-[10px] font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2 py-0.5 rounded">مفعل ونشط ✓</span>
                </div>

                <div className="flex items-center justify-between p-3 bg-slate-950/50 border border-slate-800 rounded-lg">
                  <div className="flex items-center gap-2">
                    <Code className="w-4 h-4 text-indigo-400" />
                    <span className="text-xs text-slate-200">مكتبة معالجة وصيانة الصور GD Image Library</span>
                  </div>
                  <span className="text-[10px] font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2 py-0.5 rounded">مفعل ونشط ✓</span>
                </div>

                <div className="flex items-center justify-between p-3 bg-slate-950/50 border border-slate-800 rounded-lg">
                  <div className="flex items-center gap-2">
                    <Lock className="w-4 h-4 text-indigo-400" />
                    <span className="text-xs text-slate-200">صلاحية الكتابة وتوليد الملفات في config/ و storage/</span>
                  </div>
                  <span className="text-[10px] font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2 py-0.5 rounded">صلاحية الكتابة متاحة ✓</span>
                </div>
              </div>
            </div>
          )}

          {/* STEP 2: DATABASE CREDENTIALS FORM */}
          {step === 2 && (
            <div className="space-y-4">
              <p className="text-xs text-slate-400 leading-relaxed">
                الرجاء إدخال بيانات الوصول لخادم قاعدة بيانات MySQL المخصصة لمشروع Almakhzoun Pro. سيقوم المثبت التلقائي بإنشاء قاعدة البيانات إذا كانت جديدة:
              </p>

              <div className="p-4 bg-slate-950/40 rounded-xl border border-slate-800 space-y-3.5">
                <div className="grid grid-cols-3 gap-3">
                  <div className="col-span-2">
                    <label className="block text-[10px] font-bold text-slate-400 mb-1">خادم قاعدة البيانات (Host)</label>
                    <input
                      type="text"
                      value={dbHost}
                      onChange={e => setDbHost(e.target.value)}
                      className="w-full text-xs px-3 py-1.5 rounded border border-slate-800 bg-slate-900 text-slate-200 focus:outline-none focus:border-indigo-500 font-sans"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-bold text-slate-400 mb-1">المنفذ (Port)</label>
                    <input
                      type="text"
                      value={dbPort}
                      onChange={e => setDbPort(e.target.value)}
                      className="w-full text-xs px-3 py-1.5 rounded border border-slate-800 bg-slate-900 text-slate-200 focus:outline-none focus:border-indigo-500 font-sans"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-[10px] font-bold text-slate-400 mb-1">اسم قاعدة البيانات (Database Name)</label>
                  <input
                    type="text"
                    value={dbName}
                    onChange={e => setDbName(e.target.value)}
                    className="w-full text-xs px-3 py-1.5 rounded border border-slate-800 bg-slate-900 text-slate-200 focus:outline-none focus:border-indigo-500 font-sans"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-[10px] font-bold text-slate-400 mb-1">اسم المستخدم لقاعدة البيانات</label>
                    <input
                      type="text"
                      value={dbUser}
                      onChange={e => setDbUser(e.target.value)}
                      className="w-full text-xs px-3 py-1.5 rounded border border-slate-800 bg-slate-900 text-slate-200 focus:outline-none focus:border-indigo-500 font-sans"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-bold text-slate-400 mb-1">الرمز السري لقاعدة البيانات</label>
                    <input
                      type="password"
                      value={dbPass}
                      onChange={e => setDbPass(e.target.value)}
                      placeholder="بدون كلمة مرور"
                      className="w-full text-xs px-3 py-1.5 rounded border border-slate-800 bg-slate-900 text-slate-200 focus:outline-none focus:border-indigo-500 font-sans"
                    />
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* STEP 3: SETUP ADMIN ACCOUNT */}
          {step === 3 && (
            <div className="space-y-4">
              <p className="text-xs text-slate-400 leading-relaxed">
                أنشئ حساب المدير العام الأول للنظام. سيمتلك هذا الحساب كافة صلاحيات الإدارة العليا ومراقبة جلسات المناديب وإعداد الفروع وعرض الإحصاءات والتقارير:
              </p>

              <div className="p-4 bg-slate-950/40 rounded-xl border border-slate-800 space-y-3">
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-[10px] font-bold text-slate-400 mb-1">الاسم بالكامل</label>
                    <input
                      type="text"
                      placeholder="مثال: المهندس محمد الشناوي"
                      value={adminName}
                      onChange={e => setAdminName(e.target.value)}
                      className="w-full text-xs px-3 py-1.5 rounded border border-slate-800 bg-slate-900 text-slate-200 focus:outline-none focus:border-indigo-500"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-bold text-slate-400 mb-1">اسم المستخدم للدخول</label>
                    <input
                      type="text"
                      placeholder="مثال: admin"
                      value={adminUser}
                      onChange={e => setAdminUser(e.target.value)}
                      className="w-full text-xs px-3 py-1.5 rounded border border-slate-800 bg-slate-900 text-slate-200 focus:outline-none focus:border-indigo-500 font-sans"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-[10px] font-bold text-slate-400 mb-1">كلمة المرور المشفرة</label>
                  <input
                    type="password"
                    placeholder="أدخل كلمة مرور قوية وسرية"
                    value={adminPass}
                    onChange={e => setAdminPass(e.target.value)}
                    className="w-full text-xs px-3 py-1.5 rounded border border-slate-800 bg-slate-900 text-slate-200 focus:outline-none focus:border-indigo-500 font-sans"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-[10px] font-bold text-slate-400 mb-1">البريد الإلكتروني (اختياري)</label>
                    <input
                      type="email"
                      placeholder="admin@example.com"
                      value={adminEmail}
                      onChange={e => setAdminEmail(e.target.value)}
                      className="w-full text-xs px-3 py-1.5 rounded border border-slate-800 bg-slate-900 text-slate-200 focus:outline-none focus:border-indigo-500 font-sans"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-bold text-slate-400 mb-1">رقم الجوال (اختياري)</label>
                    <input
                      type="text"
                      placeholder="0500000000"
                      value={adminPhone}
                      onChange={e => setAdminPhone(e.target.value)}
                      className="w-full text-xs px-3 py-1.5 rounded border border-slate-800 bg-slate-900 text-slate-200 focus:outline-none focus:border-indigo-500 font-sans"
                    />
                  </div>
                </div>
              </div>

              {consoleLogs.length > 0 && (
                <div className="bg-slate-950 p-3 rounded-lg border border-slate-800">
                  <span className="text-[10px] text-indigo-400 font-bold block mb-1.5 flex items-center gap-1">
                    <Terminal className="w-3.5 h-3.5" />
                    <span>مخرجات التنفيذ الفوري وقاعدة البيانات:</span>
                  </span>
                  <div className="font-mono text-[9px] text-slate-300 space-y-1 overflow-y-auto max-h-[120px] leading-relaxed">
                    {consoleLogs.map((log, i) => (
                      <p key={i}>{log}</p>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* STEP 4: SUCCESS AND SUMMARY */}
          {step === 4 && (
            <div className="space-y-4">
              <div className="p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-xl text-center space-y-2">
                <CheckCircle className="w-12 h-12 text-emerald-400 mx-auto" />
                <h4 className="font-extrabold text-sm text-emerald-400">تهانينا! تم التثبيت والتهيئة أمنياً بنجاح!</h4>
                <p className="text-xs text-slate-400">تم تهيئة ملفات السيرفر وقاعدة البيانات وملحقات الرقابة بنجاح</p>
              </div>

              <div className="p-4 bg-slate-950/45 border border-slate-800 rounded-xl space-y-2.5 text-xs text-slate-300">
                <p className="font-bold text-slate-200 border-b border-slate-800 pb-1.5">الملفات التي تم توليدها وتثبيتها في السيرفر:</p>
                
                <div className="flex justify-between items-center bg-slate-900/50 p-2.5 rounded border border-slate-800/80">
                  <div>
                    <span className="font-bold text-slate-200 block text-xs">config/config.php</span>
                    <span className="text-[10px] text-slate-500 block">ملف تهيئة قاعدة البيانات والتطبيقات المشفرة</span>
                  </div>
                  <button 
                    onClick={downloadConfigPhp}
                    className="px-2.5 py-1 text-[10px] font-bold bg-indigo-600 hover:bg-indigo-700 text-white rounded transition flex items-center gap-1 cursor-pointer"
                  >
                    <Download className="w-3 h-3" />
                    <span>تحميل ملف PHP</span>
                  </button>
                </div>

                <div className="flex justify-between items-center bg-slate-900/50 p-2.5 rounded border border-slate-800/80">
                  <div>
                    <span className="font-bold text-slate-200 block text-xs">storage/install.lock</span>
                    <span className="text-[10px] text-slate-500 block">تم إنشاء ملف قفل التثبيت تلقائياً لحماية قاعدة البيانات</span>
                  </div>
                  <span className="text-[10px] bg-emerald-500/10 text-emerald-400 px-2 py-0.5 rounded font-bold">مؤمن أمنياً ✓</span>
                </div>

                <div className="flex justify-between items-center bg-slate-900/50 p-2.5 rounded border border-slate-800/80">
                  <div>
                    <span className="font-bold text-slate-200 block text-xs">database/database.sql</span>
                    <span className="text-[10px] text-slate-500 block">تم استيراد الجداول وربط العلاقات والمفاتيح بنجاح</span>
                  </div>
                  <span className="text-[10px] bg-indigo-500/10 text-indigo-400 px-2 py-0.5 rounded font-bold">تم الاستيراد ✓</span>
                </div>
              </div>
            </div>
          )}

        </div>

        {/* Footer controls */}
        <div className="p-4 border-t border-slate-800 bg-slate-950/20 flex justify-between items-center">
          <div>
            {step === 1 && (
              <button
                onClick={() => setStep(2)}
                className="px-4 py-2 text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg transition flex items-center gap-1.5 cursor-pointer shadow-md shadow-indigo-950/20 ml-auto mr-0"
              >
                <span>الخطوة التالية (قاعدة البيانات)</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            )}

            {step === 2 && (
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setStep(1)}
                  className="px-4 py-2 text-xs font-bold text-slate-400 hover:text-white bg-slate-800 hover:bg-slate-750 rounded-lg transition flex items-center gap-1.5 cursor-pointer"
                >
                  <ArrowLeft className="w-4 h-4" />
                  <span>السابق</span>
                </button>
                <button
                  onClick={runTestConnection}
                  disabled={loading}
                  className="px-4 py-2 text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg transition flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
                >
                  {loading ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      <span>جاري فحص الاتصال بقاعدة البيانات...</span>
                    </>
                  ) : (
                    <>
                      <span>الاتصال وتهيئة قاعدة البيانات</span>
                      <ArrowRight className="w-4 h-4" />
                    </>
                  )}
                </button>
              </div>
            )}

            {step === 3 && (
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setStep(2)}
                  className="px-4 py-2 text-xs font-bold text-slate-400 hover:text-white bg-slate-800 hover:bg-slate-750 rounded-lg transition flex items-center gap-1.5 cursor-pointer"
                >
                  <ArrowLeft className="w-4 h-4" />
                  <span>السابق</span>
                </button>
                <button
                  onClick={runInstallerAndCreateAdmin}
                  disabled={loading}
                  className="px-4 py-2 text-xs font-bold text-white bg-gradient-to-r from-emerald-600 to-emerald-500 hover:from-emerald-700 hover:to-emerald-600 rounded-lg transition flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
                >
                  {loading ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      <span>جاري تشغيل المعالج وتثبيت الجداول...</span>
                    </>
                  ) : (
                    <>
                      <span>تثبيت الجداول وبدء التشغيل النهائي</span>
                      <ArrowRight className="w-4 h-4" />
                    </>
                  )}
                </button>
              </div>
            )}

            {step === 4 && (
              <button
                onClick={onClose}
                className="px-5 py-2 text-xs font-bold text-white bg-gradient-to-r from-indigo-600 to-indigo-500 hover:from-indigo-700 hover:to-indigo-600 rounded-lg transition flex items-center gap-1.5 cursor-pointer shadow-lg shadow-indigo-950/30 ml-auto mr-0"
              >
                <span>الدخول وتجربة النظام بالكامل 🎉</span>
              </button>
            )}
          </div>
        </div>

      </div>
    </div>
  );
}
