<?php
/**
 * Almakhzoun Pro - Professional PHP Installation Wizard
 * PSR-12 Compliant, Secure, PDO-based, Arabic UI
 * SPDX-License-Identifier: Apache-2.0
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

define('CONFIG_FILE', dirname(__DIR__) . '/config/config.php');
define('LOCK_FILE', dirname(__DIR__) . '/storage/install.lock');
define('SQL_FILE', dirname(__DIR__) . '/database/database.sql');

// Ensure storage and config directories exist
if (!is_dir(dirname(LOCK_FILE))) {
    @mkdir(dirname(LOCK_FILE), 0755, true);
}
if (!is_dir(dirname(CONFIG_FILE))) {
    @mkdir(dirname(CONFIG_FILE), 0755, true);
}

// 1. Safety Check: If already installed and configured, block access
if (file_exists(LOCK_FILE) && file_exists(CONFIG_FILE)) {
    die('<!DOCTYPE html>
    <html lang="ar" dir="rtl">
    <head>
        <meta charset="UTF-8">
        <title>النظام مثبت بالفعل - Almakhzoun Pro</title>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Noto+Kufi+Arabic:wght@400;500;700;800&display=swap" rel="stylesheet">
        <style>
            body { font-family: "Noto Kufi Arabic", sans-serif; background-color: #0f172a; color: #f1f5f9; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; }
            .card { background-color: #1e293b; border: 1px solid #334155; border-radius: 16px; padding: 32px; max-width: 500px; text-align: center; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.5); }
            h1 { color: #f43f5e; font-size: 24px; margin-top: 0; }
            p { color: #94a3b8; font-size: 14px; line-height: 1.8; }
            .btn { display: inline-block; background-color: #4f46e5; color: white; padding: 10px 24px; border-radius: 8px; text-decoration: none; font-weight: bold; margin-top: 16px; font-size: 13px; }
        </style>
    </head>
    <body>
        <div class="card">
            <h1>⛔ تم إيقاف معالج التثبيت لدواعي أمنية!</h1>
            <p>لقد تم تثبيت نظام Almakhzoun Pro بنجاح مسبقاً. إذا كنت تريد إعادة تشغيل معالج التثبيت، يرجى حذف ملف القفل أمنياً من السيرفر: <br><code style="color:#f43f5e; font-family: monospace; display:block; margin:8px 0; background:#0f172a; padding:6px; border-radius:4px;">storage/install.lock</code></p>
            <a href="../index.html" class="btn">الانتقال للرئيسية</a>
        </div>
    </body>
    </html>');
}

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

// Helper function to write config file
function writeConfigFile($host, $port, $dbname, $username, $password) {
    $configContent = "<?php\n";
    $configContent .= "/**\n";
    $configContent .= " * Generated by Almakhzoun Pro Installation Wizard\n";
    $configContent .= " * " . date('Y-m-d H:i:s') . "\n";
    $configContent .= " */\n\n";
    $configContent .= "return [\n";
    $configContent .= "    'db' => [\n";
    $configContent .= "        'host' => '" . addslashes($host) . "',\n";
    $configContent .= "        'port' => " . (int)$port . ",\n";
    $configContent .= "        'dbname' => '" . addslashes($dbname) . "',\n";
    $configContent .= "        'username' => '" . addslashes($username) . "',\n";
    $configContent .= "        'password' => '" . addslashes($password) . "',\n";
    $configContent .= "        'charset' => 'utf8mb4',\n";
    $configContent .= "    ],\n";
    $configContent .= "    'app' => [\n";
    $configContent .= "        'name' => 'Almakhzoun Pro ERP',\n";
    $configContent .= "        'version' => '2.0.0',\n";
    $configContent .= "        'installed_at' => '" . date('c') . "',\n";
    $configContent .= "    ]\n";
    $configContent .= "];\n";

    return file_put_contents(CONFIG_FILE, $configContent) !== false;
}

// Requirements Checks
$requirements = [
    'php_version' => version_compare(PHP_VERSION, '8.2.0', '>='),
    'pdo' => extension_loaded('pdo'),
    'pdo_mysql' => extension_loaded('pdo_mysql'),
    'gd' => extension_loaded('gd'),
    'zip' => extension_loaded('zip'),
    'config_writable' => is_writable(dirname(CONFIG_FILE)) || @chmod(dirname(CONFIG_FILE), 0777),
    'storage_writable' => is_writable(dirname(LOCK_FILE)) || @chmod(dirname(LOCK_FILE), 0777),
];

$allOk = !in_array(false, $requirements, true);

// Handle POST actions per step
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($step === 2) {
        // Step 2: Database Connection Configuration
        $host = $_POST['db_host'] ?? '127.0.0.1';
        $port = $_POST['db_port'] ?? '3306';
        $dbname = $_POST['db_name'] ?? '';
        $username = $_POST['db_user'] ?? '';
        $password = $_POST['db_pass'] ?? '';

        if (empty($dbname) || empty($username)) {
            $error = 'يرجى ملء جميع الحقول المطلوبة لقاعدة البيانات.';
        } else {
            try {
                // Test Connection
                $dsn = "mysql:host=$host;port=$port;charset=utf8mb4";
                $pdo = new PDO($dsn, $username, $password, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_TIMEOUT => 5
                ]);

                // Try to create Database if not exists
                $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbname` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
                
                // Save DB Config to Session or post fields
                session_start();
                $_SESSION['db_host'] = $host;
                $_SESSION['db_port'] = $port;
                $_SESSION['db_name'] = $dbname;
                $_SESSION['db_user'] = $username;
                $_SESSION['db_pass'] = $password;

                header('Location: ?step=3');
                exit;
            } catch (PDOException $e) {
                $error = 'فشل الاتصال بقاعدة البيانات! الخطأ الفني: ' . $e->getMessage();
            }
        }
    } elseif ($step === 3) {
        // Step 3: Admin Account Configuration
        session_start();
        $host = $_SESSION['db_host'] ?? '';
        $port = $_SESSION['db_port'] ?? '';
        $dbname = $_SESSION['db_name'] ?? '';
        $username = $_SESSION['db_user'] ?? '';
        $password = $_SESSION['db_pass'] ?? '';

        $admin_user = $_POST['admin_user'] ?? '';
        $admin_pass = $_POST['admin_pass'] ?? '';
        $admin_name = $_POST['admin_name'] ?? '';
        $admin_email = $_POST['admin_email'] ?? '';
        $admin_phone = $_POST['admin_phone'] ?? '';

        if (empty($admin_user) || empty($admin_pass) || empty($admin_name)) {
            $error = 'اسم المستخدم وكلمة المرور والاسم بالكامل حقول إجبارية.';
        } else {
            try {
                // Connect and Import database.sql
                $dsn = "mysql:host=$host;port=$port;dbname=$dbname;charset=utf8mb4";
                $pdo = new PDO($dsn, $username, $password, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
                ]);

                if (file_exists(SQL_FILE)) {
                    // Pre-installation Schema Check for Existing Tables (Auto Schema Evolution)
                    try {
                        $tblQuery = $pdo->query("SHOW TABLES LIKE 'settings'");
                        $hasTable = false;
                        if ($tblRow = $tblQuery->fetch()) {
                            $hasTable = true;
                        }
                        if ($hasTable) {
                            // Settings table exists, check for and add missing columns
                            $existingSettingsCols = [];
                            $colsQuery = $pdo->query("SHOW COLUMNS FROM `settings`");
                            while ($col = $colsQuery->fetch(PDO::FETCH_ASSOC)) {
                                $existingSettingsCols[strtolower($col['Field'])] = true;
                            }
                            
                            $colsToEnsure = [
                                'email' => "ALTER TABLE `settings` ADD COLUMN `email` varchar(150) DEFAULT NULL",
                                'company_description' => "ALTER TABLE `settings` ADD COLUMN `company_description` text DEFAULT NULL",
                                'vision' => "ALTER TABLE `settings` ADD COLUMN `vision` text DEFAULT NULL",
                                'mission' => "ALTER TABLE `settings` ADD COLUMN `mission` text DEFAULT NULL",
                                'goals' => "ALTER TABLE `settings` ADD COLUMN `goals` text DEFAULT NULL",
                                'website' => "ALTER TABLE `settings` ADD COLUMN `website` varchar(150) DEFAULT NULL",
                                'social_twitter' => "ALTER TABLE `settings` ADD COLUMN `social_twitter` varchar(255) DEFAULT NULL",
                                'social_facebook' => "ALTER TABLE `settings` ADD COLUMN `social_facebook` varchar(255) DEFAULT NULL",
                                'social_instagram' => "ALTER TABLE `settings` ADD COLUMN `social_instagram` varchar(255) DEFAULT NULL",
                                'social_linkedin' => "ALTER TABLE `settings` ADD COLUMN `social_linkedin` varchar(255) DEFAULT NULL",
                                'showroom_header_title' => "ALTER TABLE `settings` ADD COLUMN `showroom_header_title` varchar(255) DEFAULT NULL",
                                'showroom_header_subtitle' => "ALTER TABLE `settings` ADD COLUMN `showroom_header_subtitle` text DEFAULT NULL",
                                'showroom_footer_text' => "ALTER TABLE `settings` ADD COLUMN `showroom_footer_text` text DEFAULT NULL",
                                'showroom_theme' => "ALTER TABLE `settings` ADD COLUMN `showroom_theme` varchar(50) DEFAULT 'indigo'",
                                'showroom_show_price' => "ALTER TABLE `settings` ADD COLUMN `showroom_show_price` tinyint(1) DEFAULT 1",
                                'showroom_show_filters' => "ALTER TABLE `settings` ADD COLUMN `showroom_show_filters` tinyint(1) DEFAULT 1",
                                'showroom_facebook' => "ALTER TABLE `settings` ADD COLUMN `showroom_facebook` varchar(255) DEFAULT NULL",
                                'showroom_twitter' => "ALTER TABLE `settings` ADD COLUMN `showroom_twitter` varchar(255) DEFAULT NULL",
                                'showroom_instagram' => "ALTER TABLE `settings` ADD COLUMN `showroom_instagram` varchar(255) DEFAULT NULL",
                                'showroom_linkedin' => "ALTER TABLE `settings` ADD COLUMN `showroom_linkedin` varchar(255) DEFAULT NULL",
                                'showroom_snapchat' => "ALTER TABLE `settings` ADD COLUMN `showroom_snapchat` varchar(255) DEFAULT NULL",
                                'showroom_youtube' => "ALTER TABLE `settings` ADD COLUMN `showroom_youtube` varchar(255) DEFAULT NULL",
                                'showroom_custom_socials' => "ALTER TABLE `settings` ADD COLUMN `showroom_custom_socials` text DEFAULT NULL",
                                'showroom_banner_image' => "ALTER TABLE `settings` ADD COLUMN `showroom_banner_image` varchar(255) DEFAULT NULL",
                                'showroom_banner_overlay_opacity' => "ALTER TABLE `settings` ADD COLUMN `showroom_banner_overlay_opacity` int DEFAULT 50",
                                'showroom_banner_opacity' => "ALTER TABLE `settings` ADD COLUMN `showroom_banner_opacity` int DEFAULT 25",
                                'showroom_banner_height' => "ALTER TABLE `settings` ADD COLUMN `showroom_banner_height` varchar(50) DEFAULT 'medium'",
                                'showroom_banner_bg_size' => "ALTER TABLE `settings` ADD COLUMN `showroom_banner_bg_size` varchar(50) DEFAULT 'cover'",
                                'showroom_banner_title_color' => "ALTER TABLE `settings` ADD COLUMN `showroom_banner_title_color` varchar(50) DEFAULT '#ffffff'",
                                'showroom_banner_subtitle_color' => "ALTER TABLE `settings` ADD COLUMN `showroom_banner_subtitle_color` varchar(50) DEFAULT '#cbd5e1'",
                                'showroom_banner_text_bg' => "ALTER TABLE `settings` ADD COLUMN `showroom_banner_text_bg` tinyint(1) DEFAULT 0",
                                'showroom_custom_pages' => "ALTER TABLE `settings` ADD COLUMN `showroom_custom_pages` text DEFAULT NULL",
                                'showroom_menu_links' => "ALTER TABLE `settings` ADD COLUMN `showroom_menu_links` text DEFAULT NULL",
                                'showroom_custom_css' => "ALTER TABLE `settings` ADD COLUMN `showroom_custom_css` text DEFAULT NULL",
                                'showroom_custom_js' => "ALTER TABLE `settings` ADD COLUMN `showroom_custom_js` text DEFAULT NULL"
                            ];
                            
                            foreach ($colsToEnsure as $colName => $alterSql) {
                                if (!isset($existingSettingsCols[strtolower($colName)])) {
                                    $pdo->exec($alterSql);
                                }
                            }
                        }

                        // Check and upgrade cars table
                        $tblCarsQuery = $pdo->query("SHOW TABLES LIKE 'cars'");
                        if ($tblCarsRow = $tblCarsQuery->fetch()) {
                            $existingCarsCols = [];
                            $colsQuery = $pdo->query("SHOW COLUMNS FROM `cars`");
                            while ($col = $colsQuery->fetch(PDO::FETCH_ASSOC)) {
                                $existingCarsCols[strtolower($col['Field'])] = true;
                            }
                            
                            $carsColsToEnsure = [
                                'sold_by_user_id' => "ALTER TABLE `cars` ADD COLUMN `sold_by_user_id` varchar(50) DEFAULT NULL",
                                'recipient_type' => "ALTER TABLE `cars` ADD COLUMN `recipient_type` varchar(255) DEFAULT NULL",
                                'sale_amount' => "ALTER TABLE `cars` ADD COLUMN `sale_amount` decimal(12,2) DEFAULT NULL",
                                'sale_customer_name' => "ALTER TABLE `cars` ADD COLUMN `sale_customer_name` varchar(255) DEFAULT NULL",
                                'sale_customer_id' => "ALTER TABLE `cars` ADD COLUMN `sale_customer_id` varchar(100) DEFAULT NULL",
                                'sale_customer_nationality' => "ALTER TABLE `cars` ADD COLUMN `sale_customer_nationality` varchar(100) DEFAULT NULL",
                                'sale_customer_phone' => "ALTER TABLE `cars` ADD COLUMN `sale_customer_phone` varchar(100) DEFAULT NULL",
                                'exit_notes' => "ALTER TABLE `cars` ADD COLUMN `exit_notes` text DEFAULT NULL"
                            ];
                            
                            foreach ($carsColsToEnsure as $colName => $alterSql) {
                                if (!isset($existingCarsCols[strtolower($colName)])) {
                                    $pdo->exec($alterSql);
                                }
                            }
                        }
                    } catch (Exception $schemaEx) {
                        // Ignore schema checking errors to allow clean install to run normally
                    }

                    $sql = file_get_contents(SQL_FILE);
                    $pdo->exec($sql);
                } else {
                    throw new Exception('ملف قاعدة البيانات الرئيسي database.sql غير موجود بالسيرفر.');
                }

                // Add Administrator (Check uniqueness first to avoid duplicate username error if re-running installer)
                $adminId = 'u-' . time();
                $hashedPassword = password_hash($admin_pass, PASSWORD_BCRYPT);
                
                $chkUsr = $pdo->prepare("SELECT `id` FROM `users` WHERE `username` = ?");
                $chkUsr->execute([$admin_user]);
                $existingUser = $chkUsr->fetch();
                
                if ($existingUser) {
                    $adminId = $existingUser['id'];
                    $stmt = $pdo->prepare("UPDATE `users` SET `password` = ?, `name` = ?, `email` = ?, `phone` = ?, `role` = 'admin' WHERE `id` = ?");
                    $stmt->execute([$hashedPassword, $admin_name, $admin_email, $admin_phone, $adminId]);
                } else {
                    $stmt = $pdo->prepare("INSERT INTO `users` (`id`, `username`, `password`, `name`, `email`, `phone`, `role`, `avatar`) VALUES (?, ?, ?, ?, ?, ?, 'admin', NULL)");
                    $stmt->execute([$adminId, $admin_user, $hashedPassword, $admin_name, $admin_email, $admin_phone]);
                }

                // Write Config File config.php
                if (!writeConfigFile($host, $port, $dbname, $username, $password)) {
                    throw new Exception('فشل في كتابة ملف الإعدادات config/config.php. يرجى مراجعة الصلاحيات.');
                }

                // Create System Audit Log
                $stmtLog = $pdo->prepare("INSERT INTO `system_logs` (`user_id`, `user_name`, `action`, `details`, `risk_level`, `ip`) VALUES (?, ?, 'التثبيت', 'تم تثبيت النظام بنجاح وإنشاء المدير الرئيسي', 'منخفض الخطورة', ?)");
                $stmtLog->execute([$adminId, $admin_name, $_SERVER['REMOTE_ADDR']]);

                // Create Lock File
                file_put_contents(LOCK_FILE, json_encode([
                    'installed_at' => date('c'),
                    'ip' => $_SERVER['REMOTE_ADDR']
                ]));

                // Success, clear session
                session_destroy();
                $success = 'تم تثبيت النظام بنجاح!';
                $step = 4;
            } catch (Exception $e) {
                $error = 'حدث خطأ أثناء إعداد النظام: ' . $e->getMessage();
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>معالج التثبيت المعتمد - Almakhzoun Pro ERP</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Noto+Kufi+Arabic:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-main: #0f172a;
            --bg-card: #1e293b;
            --border: #334155;
            --text-primary: #f1f5f9;
            --text-secondary: #94a3b8;
            --primary: #4f46e5;
            --primary-hover: #4338ca;
            --success: #10b981;
            --danger: #ef4444;
        }
        body {
            font-family: 'Noto Kufi Arabic', sans-serif;
            background-color: var(--bg-main);
            color: var(--text-primary);
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
        }
        .container {
            width: 100%;
            max-width: 650px;
            padding: 16px;
            box-sizing: border-box;
        }
        .header {
            text-align: center;
            margin-bottom: 24px;
        }
        .logo-text {
            font-size: 26px;
            font-weight: 800;
            color: #ffffff;
            letter-spacing: -0.5px;
            margin: 0;
        }
        .logo-text span {
            color: #6366f1;
        }
        .subtitle {
            font-size: 13px;
            color: var(--text-secondary);
            margin-top: 6px;
        }
        .card {
            background-color: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: 16px;
            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.4), 0 10px 10px -5px rgba(0, 0, 0, 0.2);
            overflow: hidden;
        }
        .card-header {
            background-color: rgba(255, 255, 255, 0.02);
            padding: 20px 24px;
            border-bottom: 1px solid var(--border);
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .card-title {
            font-size: 15px;
            font-weight: 700;
            margin: 0;
        }
        .step-indicator {
            font-size: 11px;
            background-color: rgba(99, 102, 241, 0.1);
            color: #818cf8;
            padding: 4px 10px;
            border-radius: 9999px;
            font-weight: 700;
        }
        .card-body {
            padding: 24px;
        }
        .alert {
            background-color: rgba(239, 68, 68, 0.1);
            border: 1px solid rgba(239, 68, 68, 0.2);
            color: #fca5a5;
            border-radius: 8px;
            padding: 14px;
            margin-bottom: 20px;
            font-size: 13px;
            line-height: 1.6;
        }
        .alert-success {
            background-color: rgba(16, 185, 129, 0.1);
            border: 1px solid rgba(16, 185, 129, 0.2);
            color: #a7f3d0;
        }
        .req-list {
            list-style: none;
            padding: 0;
            margin: 0 0 24px 0;
        }
        .req-item {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 12px;
            background-color: rgba(255, 255, 255, 0.01);
            border: 1px solid var(--border);
            border-radius: 8px;
            margin-bottom: 10px;
            font-size: 13px;
        }
        .req-label {
            display: flex;
            align-items: center;
            gap: 8px;
        }
        .status-badge {
            font-size: 11px;
            font-weight: 700;
            padding: 2px 8px;
            border-radius: 6px;
        }
        .status-badge.ok {
            background-color: rgba(16, 185, 129, 0.1);
            color: #34d399;
        }
        .status-badge.fail {
            background-color: rgba(239, 68, 68, 0.1);
            color: #f87171;
        }
        .form-group {
            margin-bottom: 16px;
        }
        .form-row {
            display: flex;
            gap: 16px;
        }
        .form-row .form-group {
            flex: 1;
        }
        label {
            display: block;
            font-size: 12px;
            font-weight: 600;
            color: var(--text-secondary);
            margin-bottom: 6px;
        }
        input {
            width: 100%;
            padding: 10px 12px;
            box-sizing: border-box;
            background-color: #0f172a;
            border: 1px solid var(--border);
            border-radius: 8px;
            color: white;
            font-family: inherit;
            font-size: 13px;
            transition: all 0.2s;
        }
        input:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 2px rgba(99, 102, 241, 0.2);
        }
        .card-footer {
            background-color: rgba(255, 255, 255, 0.01);
            padding: 16px 24px;
            border-top: 1px solid var(--border);
            display: flex;
            justify-content: flex-end;
            gap: 12px;
        }
        .btn {
            background-color: var(--primary);
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 8px;
            font-family: inherit;
            font-size: 13px;
            font-weight: 700;
            cursor: pointer;
            transition: all 0.2s;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            text-decoration: none;
        }
        .btn:hover {
            background-color: var(--primary-hover);
        }
        .btn:disabled {
            background-color: #475569;
            color: #94a3b8;
            cursor: not-allowed;
        }
        .progress-bar-container {
            width: 100%;
            height: 4px;
            background-color: var(--border);
            position: relative;
        }
        .progress-bar {
            height: 100%;
            background-color: #6366f1;
            transition: width 0.3s;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="header">
        <h1 class="logo-text">Almakhzoun<span>Pro</span></h1>
        <p class="subtitle">نظام الإدارة المتكاملة لمعارض وصالات السيارات</p>
    </div>

    <div class="card">
        <div class="progress-bar-container">
            <div class="progress-bar" style="width: <?php echo ($step * 25); ?>%;"></div>
        </div>
        <div class="card-header">
            <h2 class="card-title">
                <?php
                if ($step === 1) echo 'الخطوة 1: فحص بيئة السيرفر والمتطلبات';
                elseif ($step === 2) echo 'الخطوة 2: تهيئة واختبار اتصال قاعدة البيانات';
                elseif ($step === 3) echo 'الخطوة 3: إعداد حساب مدير النظام الأول';
                elseif ($step === 4) echo 'اكتمل التثبيت بنجاح!';
                ?>
            </h2>
            <span class="step-indicator">الخطوة <?php echo $step; ?> من 4</span>
        </div>

        <form method="POST" action="">
            <div class="card-body">
                <?php if ($error): ?>
                    <div class="alert">⚠️ <?php echo htmlspecialchars($error); ?></div>
                <?php endif; ?>

                <?php if ($step === 1): ?>
                    <p class="subtitle" style="margin-bottom: 20px;">يقوم المعالج بفحص إعدادات ومميزات السيرفر للتأكد من قدرته على تشغيل النظام بكفاءة:</p>
                    <ul class="req-list">
                        <li class="req-item">
                            <div class="req-label">
                                <span>إصدار PHP (8.2.0 أو أحدث)</span>
                                <span style="font-size:11px; color:var(--text-secondary);">(الحالي: <?php echo PHP_VERSION; ?>)</span>
                            </div>
                            <span class="status-badge <?php echo $requirements['php_version'] ? 'ok' : 'fail'; ?>">
                                <?php echo $requirements['php_version'] ? 'متوافق ✓' : 'غير متوافق ✗'; ?>
                            </span>
                        </li>
                        <li class="req-item">
                            <span class="req-label">امتداد قاعدة البيانات PDO Extension</span>
                            <span class="status-badge <?php echo $requirements['pdo'] ? 'ok' : 'fail'; ?>">
                                <?php echo $requirements['pdo'] ? 'مفعل ✓' : 'غير مفعل ✗'; ?>
                            </span>
                        </li>
                        <li class="req-item">
                            <span class="req-label">امتداد اتصال PDO MySQL Driver</span>
                            <span class="status-badge <?php echo $requirements['pdo_mysql'] ? 'ok' : 'fail'; ?>">
                                <?php echo $requirements['pdo_mysql'] ? 'مفعل ✓' : 'غير مفعل ✗'; ?>
                            </span>
                        </li>
                        <li class="req-item">
                            <span class="req-label">مكتبة معالجة الصور GD Library</span>
                            <span class="status-badge <?php echo $requirements['gd'] ? 'ok' : 'fail'; ?>">
                                <?php echo $requirements['gd'] ? 'مفعل ✓' : 'غير مفعل ✗'; ?>
                            </span>
                        </li>
                        <li class="req-item">
                            <span class="req-label">امتداد ضغط الملفات ZIP Extension</span>
                            <span class="status-badge <?php echo $requirements['zip'] ? 'ok' : 'fail'; ?>">
                                <?php echo $requirements['zip'] ? 'مفعل ✓' : 'غير مفعل ✗'; ?>
                            </span>
                        </li>
                        <li class="req-item">
                            <span class="req-label">صلاحية الكتابة لمجلد الإعدادات config/</span>
                            <span class="status-badge <?php echo $requirements['config_writable'] ? 'ok' : 'fail'; ?>">
                                <?php echo $requirements['config_writable'] ? 'متاح للكتابة ✓' : 'مغلق ✗'; ?>
                            </span>
                        </li>
                        <li class="req-item">
                            <span class="req-label">صلاحية الكتابة لمجلد التخزين storage/</span>
                            <span class="status-badge <?php echo $requirements['storage_writable'] ? 'ok' : 'fail'; ?>">
                                <?php echo $requirements['storage_writable'] ? 'متاح للكتابة ✓' : 'مغلق ✗'; ?>
                            </span>
                        </li>
                    </ul>

                <?php elseif ($step === 2): ?>
                    <p class="subtitle" style="margin-bottom: 20px;">الرجاء إدخال بيانات الاتصال بقاعدة بيانات MySQL الخاصة بك. سيحاول المعالج إنشاء قاعدة البيانات تلقائياً إذا لم تكن موجودة:</p>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="db_host">عنوان سيرفر قاعدة البيانات (Host)</label>
                            <input type="text" id="db_host" name="db_host" value="127.0.0.1" required>
                        </div>
                        <div class="form-group">
                            <label for="db_port">المنفذ (Port)</label>
                            <input type="text" id="db_port" name="db_port" value="3306" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="db_name">اسم قاعدة البيانات (Database Name)</label>
                        <input type="text" id="db_name" name="db_name" placeholder="almakhzoun_db" required>
                    </div>

                    <div class="form-group">
                        <label for="db_user">اسم مستخدم قاعدة البيانات (Username)</label>
                        <input type="text" id="db_user" name="db_user" placeholder="root" required>
                    </div>

                    <div class="form-group">
                        <label for="db_pass">كلمة مرور قاعدة البيانات (Password)</label>
                        <input type="password" id="db_pass" name="db_pass" placeholder="اتركها فارغة إن لم توجد">
                    </div>

                <?php elseif ($step === 3): ?>
                    <p class="subtitle" style="margin-bottom: 20px;">قم بإنشاء حساب المدير الرئيسي للنظام للتحكم الكامل بصلاحيات المناديب والفروع والمخزون:</p>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="admin_name">اسم المدير بالكامل</label>
                            <input type="text" id="admin_name" name="admin_name" placeholder="مثال: محمد الشناوي" required>
                        </div>
                        <div class="form-group">
                            <label for="admin_user">اسم المستخدم لتسجيل الدخول</label>
                            <input type="text" id="admin_user" name="admin_user" placeholder="مثال: admin" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="admin_pass">كلمة المرور (سرية وقوية)</label>
                        <input type="password" id="admin_pass" name="admin_pass" placeholder="••••••••" required>
                    </div>

                    <div class="form-row">
                        <div class="form-group">
                            <label for="admin_email">البريد الإلكتروني</label>
                            <input type="email" id="admin_email" name="admin_email" placeholder="admin@example.com">
                        </div>
                        <div class="form-group">
                            <label for="admin_phone">رقم الجوال</label>
                            <input type="text" id="admin_phone" name="admin_phone" placeholder="0500000000">
                        </div>
                    </div>

                <?php elseif ($step === 4): ?>
                    <div class="alert alert-success" style="margin-bottom: 24px;">
                        🎉 تهانينا! تم تثبيت Almakhzoun Pro ERP وتهيئة النظام بنجاح تام!
                    </div>

                    <div style="font-size: 13px; line-height: 1.8; color: var(--text-secondary); space-y-3">
                        <p>تم إنجاز العمليات التالية بنجاح:</p>
                        <div style="background-color: rgba(0,0,0,0.2); padding: 16px; border-radius: 8px; border: 1px solid var(--border); font-family: monospace; font-size:11px; color:#a7f3d0;">
                            ✓ تم استيراد الجداول الرئيسية بنجاح من database.sql <br>
                            ✓ تم إدراج معارض وصالات السيارات الافتراضية بنجاح <br>
                            ✓ تم إنشاء حساب المدير الرئيسي وصلاحيات الرقابة <br>
                            ✓ تم توليد ملف الإعدادات config/config.php بنجاح <br>
                            ✓ تم قفل معالج التثبيت أمنياً عبر إنشاء storage/install.lock
                        </div>
                        <p style="margin-top: 16px; color: var(--text-primary); font-weight:600;">
                            يرجى التوجه إلى شاشة تسجيل الدخول للدخول باسم المستخدم والرمز السري الذي اخترته.
                        </p>
                    </div>
                <?php endif; ?>
            </div>

            <div class="card-footer">
                <?php if ($step === 1): ?>
                    <button type="button" onclick="window.location.reload();" class="btn" style="background-color:#475569;">تحديث الفحص</button>
                    <a href="?step=2" class="btn" <?php echo !$allOk ? 'disabled' : ''; ?>>متابعة التثبيت ←</a>
                <?php elseif ($step === 2): ?>
                    <a href="?step=1" class="btn" style="background-color:#475569;">السابق</a>
                    <button type="submit" class="btn">اختبار الاتصال وحفظ لقاعدة البيانات ←</button>
                <?php elseif ($step === 3): ?>
                    <a href="?step=2" class="btn" style="background-color:#475569;">السابق</a>
                    <button type="submit" class="btn">تهيئة الجداول وإنشاء المدير الفوري ←</button>
                <?php elseif ($step === 4): ?>
                    <a href="../index.html" class="btn" style="background-color:var(--success);">الذهاب للوحة التحكم وتسجيل الدخول 🎉</a>
                <?php endif; ?>
            </div>
        </form>
    </div>
</div>

</body>
</html>
